# frozen_string_literal: true

source 'https://rubygems.org'

gem 'fluent-plugin-kubernetes_metadata_filter', '~> 2.2.0'
gem 'fluent-plugin-multi-format-parser', '~> 1.0.0'
gem 'fluent-plugin-prometheus', '~> 1.5.0'
gem 'fluent-plugin-systemd', '~> 1.0.2'
gem 'fluentd', '1.7.0'
